#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
ARGS=${ARGS}
----------------------------------------------------------------------
"
# Copy config.yml if it doesn't exist
if [[ ! -f "${CONFIG_DIR}/config.yml" ]]; then
    echo "Installing default \"config.yml\"..."
    cp "${APP_DIR}/config.yml.sample" "${CONFIG_DIR}/config.yml"
    find "${CONFIG_DIR}" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi