#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------

----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.yml" ]]; then
    echo "Installing default \"config.yml\"..."
    cp "${APP_DIR}/config/config.yml.sample" "${CONFIG_DIR}/config.yml"
    find "${CONFIG_DIR}/config.yml" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

# Create data folder and set permissions
echo "Setting up data folder..."
mkdir -p "${CONFIG_DIR}/data"
chmod "=rwx" "${CONFIG_DIR}/data"
find "${CONFIG_DIR}/data" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +

# Set up MPLCONFIGDIR
echo "Setting up MPLCONFIGDIR..."
mkdir -p "${MPLCONFIGDIR}"
chmod "=rwx" "${MPLCONFIGDIR}"
find "${MPLCONFIGDIR}" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +

echo "Permissions applied successfully."
