#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

cd "${CONFIG_DIR}" || exit 1
# shellcheck disable=SC2086
exec s6-setuidgid hotio python3 "${APP_DIR}/main.py" --config-file "${CONFIG_DIR}/config.yml" --data-folder "${CONFIG_DIR}/data" --log-folder "${CONFIG_DIR}/logs"
