name: call-build

on:
  workflow_dispatch:
  push:
    branches-ignore:    
      - 'master'

jobs:
  call:
    uses: engels74/docker-build-workflow/.github/workflows/build-on-call.yml@master
    secrets: inherit
